{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":1080,
    "password":"m4_getenv_req(SHADOWSOCKS_PASSWORD)",
    "local_address":"m4_getenv_req(SHADOWSOCKS_OUTGOING_IP)",
    "timeout":60,
    "method":"chacha20-ietf-poly1305"
}
